### ISSUE TITLE
Load saved whiteboard

### ISSUE THREAD

**Issue by mukund-m** [mostafazke/ng-whiteboard#11]
Hi,
Is there a way I can re-load already saved whiteboard content ? I know we might need save the data in svg or any other custom format that you can use to repaint the board.

**Comment by mostafazke** [comment]
Sorry for the late response, check the latest version.

**Comment by CodeTriager** [comment]
Hi can you just tell what the methods for this are called or provide a short piece of code? I haven't found a method for that in the documentation (which is not working for your types on the website just fyi)
