### ISSUE TITLE
how to get photo drawn base64?

### ISSUE THREAD

**Issue by clark-97** [mostafazke/ng-whiteboard#13]
this.whiteboardService.save() can only save photo as a file, i want to get photo base64 to save into mongodb, how to get it ?

**Comment by clark-97** [comment]
Or get the drawn photo object, so that I can re-edit it in the future.

**Comment by hareeshreddy13** [comment]
did you find solution?

**Comment by clark-97** [comment]
> did you find solution?

Yup, I will make a pull request later @hareeshreddy13

**Comment by mostafazke** [comment]
@clark-97 @hareeshreddy13 
Now you can pass 'base64' to the save method and receive the base 64 string on (save) event.

**Comment by hareeshreddy13** [comment]
Thank you Moustafa Zaki.
