### ISSUE TITLE
Can's save image in firefox

### ISSUE THREAD

**Issue by DenseOriginal** [mostafazke/ng-whiteboard#14]
Firefox does not support drawing SVG images to canvas unless the SVG file has width/height attributes on the root `<svg>` element and those width/height attributes are not percentages. This is a longstanding [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=700533).

You can fix this error by setting width and height on the canvas right before trying to save the image.

**Comment by mostafazke** [comment]
Thanks @DenseOriginal for your help.
It's fixed now on version [1.4.6](https://www.npmjs.com/package/ng-whiteboard/v/1.4.6)
