### ISSUE TITLE
Not able to install on Angular 16

### ISSUE THREAD

**Issue by rafaelcastrodev** [mostafazke/ng-whiteboard#140]
Issue:
Unable to resolve dependency tree
Could not resolve dependency:
peer @angular/common@"^14.0.0" from ng-whiteboard@2.0.16

I tried with --force and --legacy-peer-deps.
It trigger another error regarding D3
Tried install D3 on my own, threw another error on angular/core and so on...

**Comment by mostafazke** [comment]
Hello @rafaelcastrodev, Sorry for the late response, I faced some trouble while upgrading the angular version from 14 to 16.
Now you can update the library to the latest version (2.0.17) to solve the problem.
