### ISSUE TITLE
Button not showing...

### ISSUE THREAD

**Issue by borisazar** [mostafazke/ng-whiteboard#17]
Everything worked fine but the buttons did not show up and I don't see this in options. Any hints?

**Comment by digimiles348** [comment]
Also facing this issue... Appreciate if someone helps

**Comment by mostafazke** [comment]
@borisazar  @digimiles348
Sorry for the late response, check the latest version. 
You can copy any example code and start working with
https://mostafazke.github.io/ng-whiteboard/examples
