### ISSUE TITLE
Touch support doesn't appear to be working

### ISSUE THREAD

**Issue by vincerogers** [mostafazke/ng-whiteboard#187]
If you access the demo site via a mobile device or through mobile emulation on Chrome dev tools, free form drawing with touch isn't working properly. It will begin drawing but then revert to scroll mode.

**Comment by mostafazke** [comment]
Hi @vincerogers,

Thank you for reporting this issue!
The problem has been resolved in the latest release, version 3.0.3.
Feel free to update to the latest version,

If you encounter any further issues or have additional feedback, please don't hesitate to let us know.

Best regards,
Mostafa.
