### ISSUE TITLE
Image not loading when using an ipad

### ISSUE THREAD

**Issue by jhonmacaraig** [mostafazke/ng-whiteboard#5]
Hello Guys,
      good day!
I was wondering if you encounter an issue , when selecting an image in ipad
the image is not loaded.

I suspect it's a permission, because when i try on android it's working fine.
but if you have time can you please do check it out please.

I appreciate if you would give me some feedback.

Sincerely yours,

Jhon

**Comment by jhonmacaraig** [comment]
Just a followup i don't think it's a permission , because when itry to upload using the browser.It's working fine.

**Comment by mostafazke** [comment]
First of all thanks Jhon for the contribution, and we'll back with feedback shortly.

**Comment by mostafazke** [comment]
@jhonmacaraig The issue has been fixed in version 1.4.1

**Comment by jhonmacaraig** [comment]
Hello Thanks, I think you introduce another error
![image](https://user-images.githubusercontent.com/1201350/80914278-1d496880-8d7d-11ea-8e13-5749e76fe44d.png)
so what i did was, i put thengWhiteboardService on the provider it's working fine but
when i add an image its not showing up anymore. 
We are not talking about the ipad  , i am using windows 10 chrome browser
