### ISSUE TITLE
'ng-whiteboard' is not a known element

### ISSUE THREAD

**Issue by MedinaAJ** [mostafazke/ng-whiteboard#6]
Hello,

First of all congratulate the developer for his component. I really like the demo.

I have done the 3 steps indicated for installation in my project, after installing the package and importing the module into my app.module.ts everything is correct.

The problem comes when I incorporate the tag <ng-whiteboard></ng-whiteboard> in my html of the component where I intend to use it.

I get an error "'ng-whiteboard' is not a known element", as if the module was not installed.

Best regards.
[editar-parte.zip](https://github.com/mostafazke/ng-whiteboard/files/4579840/editar-parte.zip)

[app.module.zip](https://github.com/mostafazke/ng-whiteboard/files/4579843/app.module.zip)

**Comment by mathildamonni** [comment]
You should import it inside the page where you want to use the component.

Regards

**Comment by mostafazke** [comment]
Sorry for the late response, check the latest version.
