### ISSUE TITLE
What does the camera icon do in the demo?

### ISSUE THREAD

**Issue by thomastthai** [mostafazke/ng-whiteboard#7]
I clicked on the camera icon, it allowed me to choose an image. After that nothing appears.

**Comment by mostafazke** [comment]
Hello @thomastthai, it was a button for image upload and it used to be worked but we had several issues in the last deployment, it works now please try it again.

**Comment by maximus1074** [comment]
I have an angular - ionic app and I want image to be uploaded without selecting anything from the file sytem. However, no matter what I have done I can't upload an image so that I wouldn't see a white background.

**Comment by moustafa-in3** [comment]
Hi, Maximus the uploading from the file system is for demo purposes only,
the correct way to insert images is to use whiteboardService like this:
```typescript
import { NgWhiteboardService } from 'ng-whiteboard';
...

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
   styleUrls: ['./app.component.scss']
   ...
)}

  constructor(private whiteboardService: NgWhiteboardService) {
   this.whiteboardService.addImage('Base64 image');
  }

```

**Comment by mostafazke** [comment]
Sorry for the late response, check the latest version.
