### ISSUE TITLE
Can't draw to Whiteboard in Ionic app

### ISSUE THREAD

**Issue by antalmate12** [mostafazke/ng-whiteboard#75]
Hello,

I'm using this package in an Ionic app, my problem is that the whiteboard doesn't recognise the draw events, only after I navigate to an other route and navigate back.

Sometimes it recognises the draw, but doesn't show the lines, but when I trigger the "undo" method the lines appear.

I'm using the "basic" example code

**Comment by antalmate12** [comment]
When I test it on mobile devices I don't even need to navigate or trigger any of the events to make the updates shown. I draw something (not showing), then I change the orientation of the device, and it's there, and it shows any other drawings without an error

**Comment by mostafazke** [comment]
@antalmate12 Could you provide a sample code
