### ISSUE TITLE
Ideas: Resizing, Layers, Text Input

### ISSUE THREAD

**Issue by thomastthai** [mostafazke/ng-whiteboard#8]
I take that the drawings are done in SVG and converted to bitmap when it's saved or downloaded. If that's the case, it would be beneficial in the demo to select each pen "stroke" or group of pen "strokes" to resize, change the fill or outline color. Then you can play with "layers" and move one in front or to the back of another. An ability to add text input would be helpful too.

**Comment by mostafazke** [comment]
@thomastthai 
Sorry for the late response, check the latest version.
