### ISSUE TITLE
THIS IS PERFECT!!!

### ISSUE THREAD

**Issue by rafaeldcastro** [mostafazke/ng-whiteboard#9]
I have one request for "improvement". I know you're busy and I'm not counting this request to ever be "heard", but is it possible to enable/insert a picture like a pen, pencil, or even an arrow (mouse like) and the brush strokes begin at the tip of this picture?

![image](https://user-images.githubusercontent.com/5839269/89937857-07550a80-dbec-11ea-840d-9a9ba3a1351e.png)

**Comment by mostafazke** [comment]
@rafaeldcastro 
Sorry for the late response, check the latest version.
